#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

#ip_v4=$(curl ifconfig.me/ip)
ip_v4=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}')

text=$(print_wrap "${WIDTH}" "${ip_v4}")

print_columns "Public IP address" "${text}"
